KVER = "2.6.28"
PSPREL = "2.1.0.1"

require linux-omap3_psp2.inc

PR = "psp${PSPREL}-r3"

SRCREV = "0ec95b96fd77036a13398c66901e11cd301190d0"

SRC_URI = "git://git.kernel.org/pub/scm/linux/kernel/git/tmlind/linux-omap-2.6.git;protocol=git"

SRC_URI_append_omap3evm = " \
file://0001-ISP-Camera-patches-applied.patch \
file://0002-TVP5146-patch-applied.patch \
file://0003-OMAP3-ISP-Camera-Added-BT656-support.patch \
file://0004-Added-OMAP3EVM-Multi-Media-Daughter-Card-Support.patch \
file://0005-001-Support-for-high-bandwidth-isochronous-trf.patch.patch \
file://0006-002-bulk-NAK-scheme.patch.patch \
file://0007-003-fix-ep-allocation-logic.patch.patch \
file://0008-004-qh-in-out-list.patch.patch \
file://0009-005-h-disable-fix.patch.patch \
file://0010-006-moduler-fix.patch.patch \
file://0011-007-config-suspend-gadget-fix.patch.patch \
file://0012-008-vbus-off-at-disconnect.patch.patch \
file://0013-009-procfs-revert.patch.patch \
file://0014-010-sdma-on-all-rx-channels.patch.patch \
file://0015-011-fix-modular-build.patch.patch \
file://0016-012-fix-compilation-error.patch.patch \
file://0017-013-null-pointer-check.patch.patch \
file://0018-014-adding-nop-xceiv.patch.patch \
file://0019-015-nop-xceiv-device-for-musb.patch.patch \
file://0020-016-add-suspend-proc-entry.patch.patch \
file://0021-017-ehci-fix-kernel-panic-at-rmmod.patch.patch \
file://0022-018-remove-otg-to-config-suspend-selection.patch.patch \
file://0023-019-fix-bug-in-musbhsdma.patch.patch \
file://0024-020-ehci-port2-gpio-and-no-port1-config.patch.patch \
file://0025-DSS-New-display-subsystem-driver-for-OMAP2-3.patch \
file://0026-DSS-OMAPFB-fb-driver-for-new-display-subsystem.patch \
file://0027-DSS-Add-generic-DVI-panel.patch \
file://0028-DSS-support-for-Beagle-Board.patch \
file://0029-DSS-Sharp-LS037V7DW01-LCD-Panel-driver.patch \
file://0030-DSS-Support-for-OMAP3-SDP-board.patch \
file://0031-DSS-Support-for-OMAP3-EVM-board.patch \
file://0032-DSS-Hacked-N810-support.patch \
file://0033-DSS-OMAPFB-allocate-fbmem-only-for-fb0-or-if-spes.patch \
file://0034-OMAPFB-remove-extra-omapfb_setup_overlay-call.patch \
file://0035-OMAPFB-fix-GFX_SYNC-to-be-compatible-with-DSS1.patch \
file://0036-DSS-Add-comments-to-FAKE_VSYNC-to-make-things-more.patch \
file://0037-OMAPFB-remove-extra-spaces.patch \
file://0038-DSS-fix-clk_get_usecount.patch \
file://0039-OMAPFB-remove-debug-print.patch \
file://0040-VRFB-testing.patch \
file://0041-OMAPFB-more-VRFB-hacks.patch \
file://0042-OMAPFB-still-more-VRFB-hacking.patch \
file://0043-V4L2-Driver-added.patch \
file://0044-Only-made-copmipled-with-Hariks-changes.patch \
file://0045-Compilation-issue-fixed-in-mux.h.patch \
file://0046-TPS6235x-based-Power-regulator-support-added.patch \
file://0047-Changes-for-adding-TPS6235x-based-PR785-board-suppor.patch \
file://0048-Audio-ASoC-Add-OMAP3-EVM-support-for-ALSA-SoC.patch \
file://0049-Fixes-for-compilation-after-integration.patch \
file://0050-021-updated-config-option-for-ES3.0.patch.patch \
file://0051-022-EHCI-support-in-ES3.0.patch.patch \
file://0052-OMAP2-3-clock-implement-clock-notifier-infrastructu.patch \
file://0053-OMAP-clock-add-notifier-infrastructure.patch \
file://0054-OMAP2-3-clock-store-planned-clock-rates-into-tempor.patch \
file://0055-OMAP2-3-clock-add-clk-post-rate-change-notifiers.patch \
file://0056-OMAP2-3-clock-add-clock-pre-rate-change-notificatio.patch \
file://0057-OMAP2-3-clock-add-clock-prepare-rate-change-notific.patch \
file://0058-OMAP2-3-clock-add-clock-abort-rate-change-notificat.patch \
file://0059-OMAP2-3-PM-create-the-OMAP-PM-interface-and-add-a-d.patch \
file://0060-OMAP2-3-omapdev-add-basic-omapdev-structure.patch \
file://0061-OMAP242x-omapdev-add-OMAP242x-omapdev-records.patch \
file://0062-OMAP243x-omapdev-add-OMAP243x-omapdev-records.patch \
file://0063-OMAP3xxx-omapdev-add-OMAP3xxx-omapdev-records.patch \
file://0064-OMAP2-3-omapdev-add-code-to-walk-the-omapdev-record.patch \
file://0065-OMAP-PM-counter-infrastructure.patch \
file://0066-OMAP-PM-Hook-into-PM-counters.patch \
file://0067-OMAP-PM-Add-closures-to-clkdm_for_each-and-pwrdm_f.patch \
file://0068-OMAP-PM-Add-pm-debug-counters.patch \
file://0069-OMAP-PM-debug-make-powerdomains-use-PM-debug-count.patch \
file://0070-OMAP-PM-debug-do-not-print-out-status-for-meta-pow.patch \
file://0071-OMAP-PM-debug-Add-PRCM-register-dump-support.patch \
file://0072-OMAP-PM-Add-definitions-for-ETK-pads-and-observabi.patch \
file://0073-OMAP-Debug-observability-and-ETK-padconf-implementa.patch \
file://0074-OMAP-Add-debug-observablity-debobs-Kconfig-item.patch \
file://0075-OMAP3-PM-GPMC-context-save-restore.patch \
file://0076-OMAP3-PM-GPIO-context-save-restore.patch \
file://0077-OMAP3-PM-I2C-context-save-restore.patch \
file://0078-OMAP3-PM-INTC-context-save-restore.patch \
file://0079-OMAP3-PM-PRCM-context-save-restore.patch \
file://0080-OMAP3-PM-Populate-scratchpad-contents.patch \
file://0081-OMAP3-PM-SCM-context-save-restore.patch \
file://0082-OMAP3-PM-SRAM-restore-function.patch \
file://0083-OMAP3-PM-handle-PER-NEON-CORE-in-idle.patch \
file://0084-OMAP3-PM-Restore-MMU-table-entry.patch \
file://0085-OMAP3-PM-MPU-off-mode-support.patch \
file://0086-OMAP3-PM-CORE-domain-off-mode-support.patch \
file://0087-OMAP3-PM-allow-runtime-enable-disable-of-OFF-mode.patch \
file://0088-OMAP3-3430SDP-minimal-kernel-defconfig.patch \
file://0089-OMAP-PM-sysfs-interface-for-enabling-voltage-off-i.patch \
file://0090-OMAP-PM-DMA-context-save-restore.patch \
file://0091-OMAP3-PM-CPUidle-Basic-support-for-C1-C2.patch \
file://0092-OMAP3-PM-CPUidle-Enables-state-C4.patch \
file://0093-OMAP3-PM-CPUidle-Enables-C3-and-C5.patch \
file://0094-OMAP3-PM-CPUidle-Safe-state-on-bm-activity.patch \
file://0095-OMAP3-PM-CPUidle-obey-enable_off_mode-flag.patch \
file://0096-OMAP3-PM-CPUidle-restrict-C-states-on-UART-activi.patch \
file://0097-OMAP3-PM-Fix-cpu-idle-init-sequencing.patch \
file://0098-OMAP-PM-off-mode-support-for-DMA-on-EMU-HS-devices.patch \
file://0099-OMAP3-SRAM-size-fix-for-HS-EMU-devices.patch \
file://0100-OMAP3-PM-off-mode-support-for-HS-EMU-devices.patch \
file://0101-OMAP3-PM-Enable-SDRAM-auto-refresh-during-sleep.patch \
file://0102-OMAP-SDRC-Add-new-register-definitions-for-SDRAM-c.patch \
file://0103-OMAP3-PM-SDRC-auto-refresh-workaround-for-off-mode.patch \
file://0104-OMAP-PM-Implement-get_last_off_on_transaction_id.patch \
file://0105-OMAP3-PM-Use-pwrdm_set_next_pwrst-instead-of-set_p.patch \
file://0106-OMAP3-SRF-Generic-shared-resource-f-w.patch \
file://0107-OMAP3-SRF-MPU-CORE-PD-latency-modeling.patch \
file://0108-OMAP3-SRF-omap3-srf-driver.patch \
file://0109-OMAP3-SRF-OMAP-PM-srf-implementation.patch \
file://0110-OMAP-SRF-Fixes-to-shared-resource-framework-Ver.3.patch \
file://0111-OMAP3-PM-Fix-wrong-sequence-in-suspend.patch \
file://0112-OMAP3-PM-decouple-PER-and-CORE-context-save-and-re.patch \
file://0113-PM-Added-three-PLL-registers-to-the-PRCM-context-sa.patch \
file://0114-PM-Changed-secure-RAM-storage-size-from-0x8000-to-0.patch \
file://0115-OMAP3-PM-Do-not-build-suspend-code-if-SUSPEND-is-n.patch \
file://0116-OMAP-PM-Build-fails-if-PM-is-not-enabled.patch \
file://0117-OMAP2-PM-Fix-omap2-build.patch \
file://0118-OMAP3-SRF-Add-CORE-rate-table-param-in-OMAP-PM.patch \
file://0119-OMAP3-SRF-Add-VDD1-VDD2-rate-tables-for-3430SDP.patch \
file://0120-OMAP3-SRF-Add-virt-clk-nodes-for-VDD1-VDD2.patch \
file://0121-OMAP3-SRF-Adds-OPP-Freq-res-s-in-SRF.patch \
file://0122-OMAP3-SRF-Update-OMAP-PM-layer.patch \
file://0123-OMAP3-SRF-Voltage-scaling-support.patch \
file://0124-OMAP3-SRF-VDD2-scaling-support.patch \
file://0125-OMAP3-SRF-Adds-sysfs-control-for-VDD1-VDD2-OPP-s.patch \
file://0126-OMAP3-PM-Replace-spinlocks-with-mutex-in-SRF.patch \
file://0127-OMAP3-PM-CPUFreq-driver-for-OMAP3.patch \
file://0128-OMAP3-PM-Update-the-min-defconfig-for-3430sdp.patch \
file://0129-OMAP3-SRF-Fix-crash-on-non-3430SDP-platforms-with-D.patch \
file://0130-Save-sram-context-after-changing-MPU-DSP-or-core-cl.patch \
file://0131-PM-Added-suspend-target-state-control-to-debugfs-fo.patch \
file://0132-OMAP2-3-PM-system_rev-omap_rev.patch \
file://0133-OMAP3-PM-Prevent-PER-from-going-OFF-when-CORE-is-g.patch \
file://0134-OMAP3-PM-Update-SSI-omapdev-record.patch \
file://0135-PM-OMAP3-Change-omap3_save_secure_ram-to-be-called.patch \
file://0136-OMAP3-PM-MPU-and-CORE-should-stay-awake-if-there-i.patch \
file://0137-OMAP3-PM-Scale-VDD2-OPP-for-VDD1-OPP3-and-higher.patch \
file://0138-OMAP3-GPIO-fixes-for-off-mode.patch \
file://0139-PM-OMAP3-Refreshed-DVFS-VDD1-control-against-lates.patch \
file://0140-ARM-MMU-add-a-Non-cacheable-Normal-executable-memo.patch \
file://0141-OMAP3-SRAM-mark-OCM-RAM-as-Non-cacheable-Normal-mem.patch \
file://0142-OMAP3-SRAM-add-ARM-barriers-to-omap3_sram_configure.patch \
file://0143-OMAP3-clock-add-interconnect-barriers-to-CORE-DPLL.patch \
file://0144-OMAP3-SRAM-clear-the-SDRC-PWRENA-bit-during-SDRC-fr.patch \
file://0145-OMAP3-SDRC-Add-166MHz-83MHz-SDRC-settings-for-the.patch \
file://0146-OMAP3-SDRC-initialize-SDRC_POWER-at-boot.patch \
file://0147-OMAP3-SRAM-renumber-registers-to-make-space-for-arg.patch \
file://0148-OMAP3-clock-only-unlock-SDRC-DLL-if-SDRC-clk-83MH.patch \
file://0149-OMAP3-clock-use-pr_debug-rather-than-pr_info-in.patch \
file://0150-OMAP3-clock-remove-wait-for-DPLL3-M2-clock-to-stabi.patch \
file://0151-OMAP3-clock-initialize-SDRC-timings-at-kernel-start.patch \
file://0152-OMAP3-clock-add-a-short-delay-when-lowering-CORE-cl.patch \
file://0153-OMAP3-clock-SDRC-program-SDRC_MR-register-during-SD.patch \
file://0154-OMAP3-SRAM-add-more-comments-on-the-SRAM-code.patch \
file://0155-OMAP3-SRAM-convert-SRAM-code-to-use-macros-rather-t.patch \
file://0156-OMAP3-Add-support-for-DPLL3-divisor-values-higher-t.patch \
file://0157-OMAP3-PM-Fixed-VDD2-control-to-work-from-both-sysf.patch \
file://0158-OMAP3-PM-Added-DVFS-OPP-locking-interface-for-VDD1.patch \
file://0159-OMAP3-Fix-rate-calculation-bug-in-omap3_select_tabl.patch \
file://0160-OMAP3-PM-Prevented-DVFS-state-switches-when-enabli.patch \
file://0161-OMAP3-PM-Enable-VDD2-OPP1.patch \
file://0162-OMAP3-PM-Fix-linker-error-without-CONFIG_PM-option.patch \
file://0163-PM-OMAP3-Removed-a-couple-of-unused-variables-from.patch \
file://0164-PM-OMAP3-Added-support-for-possibly-failing-clk_se.patch \
file://0165-Fix-omap_getspeed.patch \
file://0166-Make-sure-omap-cpufreq-driver-initializes-after-cpuf.patch \
file://0167-VRFB-rotation-at-compile-time-supported.patch \
file://0168-Minor-Fixes-to-V4L2-driver.patch \
file://0169-Minor-Fixes-in-DSS-library.patch \
file://0170-Kconfig-option-added-to-select-overlay-manager.patch \
file://0171-Merged-Latest-Tomi-s-changes.patch \
file://0172-file-mode-restored-back.patch \
file://0173-Resizer-issues-fixed-in-1.0.2-release.patch \
file://0174-old-FBDEV-made-working.patch \
file://0175-DVI-720P-and-480P-support-added.patch \
file://0176-Audio-ASoC-Fixing-audio-capture-issue.patch \
file://0177-Backlight-driver-for-omap3evm.patch \
file://0178-Audio-Applying-spinlock-deadlock-patch-sent-by-Stan.patch \
file://0179-Revert-ARM-OMAP3-Enable-writing-to-XCCR-and-RCCR.patch \
file://0180-Add-support-for-OMAP35x-processors.patch \
file://0181-Runitme-check-for-OMAP35x.patch \
file://0182-Updates-for-OMAP3EVM.patch \
file://0183-OMAP3EVM-MMC1-support-for-TPS-based-PR785-power-modu.patch \
file://0184-Kconfig-option-for-Camera-and-V4L2-DSS2-is-fixed.patch \
file://0185-Temperory-workarond-for-ISP-CCDC-hang-issue.patch \
file://0186-Warning-fixed.patch \
file://0187-023-fix-ehci-while-loop-stuck-when-insmod.patch.patch \
file://0188-OMAP35x-Update-default-configuration-for-OMAP3EVM.patch \
file://0189-OMAP35x-enable-CPUIDLE-in-default-configuration.patch \
file://0190-VRFB-address-calculation-bug-fixed.patch \
file://0191-added-omap_silicon_rev-at-arch-arm-plat-omap-incl.patch \
file://0192-024-ehci-fix-for-silicon-rev-changes.patch.patch \
file://0193-update-defconfig-for-kernel-debug-and-musb-debug.pat.patch \
"
