#! /bin/sh

am1xdemo="/usr/tests/am1x-demo"

test -x "$am1xdemo" || exit 0
grep -e "AM18xx EVM" -e "AM17xx EVM" /proc/cpuinfo >/dev/null 2>&1 || exit 0

export LD_LIBRARY_PATH=/usr/lib
export TSLIB_PLUGINDIR=/usr/lib/ts
export TSLIB_TSDEVICE=/dev/input/touchscreen0
export TSLIB_CONFFILE=/etc/ts.conf
export QWS_MOUSE_PROTO=Tslib:/dev/input/touchscreen0

case "$1" in
  start)
    echo -n "Starting AM1x Demo application"
    if [ ! -f /etc/pointercal ] ; then
        ts_calibrate
    fi
    start-stop-daemon --start --quiet --background --exec $am1xdemo
    echo "."
    ;;
  stop)
    echo -n "Stopping AM1x Demo application"
    start-stop-daemon --stop --quiet --pidfile /var/run/am1x-demo.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/am1x-demo {start|stop}"
    exit 1
esac

exit 0
